# Generated by Django 5.1.15 on 2026-05-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikirevision',
            name='base_body',
            field=models.TextField(blank=True, default='', help_text='Page body at the moment this revision was started.'),
        ),
        migrations.AddField(
            model_name='wikirevision',
            name='base_title',
            field=models.CharField(blank=True, default='', help_text='Page title at the moment this revision was started.', max_length=200),
        ),
    ]
