# Generated by Django 5.1.15 on 2026-04-30 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('maintainer', 'Maintainer'), ('contributor', 'Contributor'), ('advisor', 'Advisor')], default='author', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('artifact_type', models.CharField(blank=True, max_length=40)),
                ('field', models.CharField(blank=True, max_length=80)),
                ('license', models.CharField(blank=True, max_length=80)),
                ('placeholder_doi', models.CharField(blank=True, help_text='Spoofed DOI of the form 10.demo/<slug> until DataCite is wired up.', max_length=80)),
                ('canonical_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributors', models.ManyToManyField(related_name='projects', through='projects.Contribution', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='people.institution')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='projects.project'),
        ),
        migrations.CreateModel(
            name='ArtifactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('github', 'GitHub repository'), ('codeberg', 'Codeberg repository'), ('zenodo', 'Zenodo deposit'), ('pdf', 'PDF'), ('cad', 'CAD files'), ('dataset', 'Dataset'), ('other', 'Other')], default='github', max_length=40)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_links', to='projects.project')),
            ],
            options={
                'ordering': ['kind', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tag')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects', through='projects.TagAssignment', to='projects.tag'),
        ),
        migrations.CreateModel(
            name='LineageEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('derived_from', 'derived from'), ('inspired_by', 'inspired by'), ('forked_from', 'forked from'), ('replaces', 'replaces')], default='derived_from', max_length=40)),
                ('note', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_parents', to='projects.project')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_children', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('parent', 'child', 'relation'), name='unique_lineage_edge'), models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='lineage_no_self_edge')],
            },
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(fields=('project', 'user', 'role'), name='unique_contribution_role'),
        ),
        migrations.AddConstraint(
            model_name='tagassignment',
            constraint=models.UniqueConstraint(fields=('project', 'tag'), name='unique_tag_assignment'),
        ),
    ]
