# Generated by Django 5.1.15 on 2026-04-30 02:15

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(blank=True, help_text='One-line plain-English description. Used for cards and search.', max_length=280),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private (only contributors and staff)'), ('public', 'Public (visible to everyone)')], default='private', help_text='Drafts default to private. Flip to public when ready to share.', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='license',
            field=models.CharField(blank=True, help_text='SPDX identifier or short name (e.g. MIT, CERN-OHL-S-2.0, CC-BY-4.0).', max_length=80),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Plain-text citation as it would appear in a references list.', max_length=600)),
                ('url', models.URLField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=120)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='projects.project')),
            ],
            options={
                'ordering': ['order', '-year', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=projects.models.project_image_upload_to)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
