# Generated by Django 5.1.15 on 2026-04-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_by_project_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readme',
            field=models.TextField(blank=True, help_text='Long-form project README. Markdown is supported.'),
        ),
    ]
