# Generated by Django 5.1.15 on 2026-04-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_readme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Deprecated. Kept for backwards compatibility; new content goes in summary or readme.'),
        ),
    ]
