# Generated by Django 5.1.15 on 2026-05-01 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image_focal_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Horizontal focal point for cover-image crops, 0-100%.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image_focal_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Vertical focal point for cover-image crops, 0-100%.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image_zoom',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Display zoom for cover-image crops. 1 is no extra zoom.', max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
