# Generated by Django 5.1.15 on 2026-05-02 12:39

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_cover_image_focal_x_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contribution',
            name='unique_contribution_per_project',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='orcid_id',
            field=models.CharField(blank=True, default='', help_text='Verified ORCID iD, populated from ORCID sign-in rather than manual entry.', max_length=19, validators=[django.core.validators.RegexValidator(message='ORCID iD must look like 0000-0000-0000-000X.', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$')]),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(condition=models.Q(('orcid_id', ''), _negated=True), fields=('project', 'orcid_id'), name='unique_contribution_per_project'),
        ),
    ]
