# Generated by Django 5.1.15 on 2026-05-02 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_contribution_unique_contribution_per_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='role',
            field=models.CharField(default='Project lead', help_text='Free text. Pick from the suggestions or write your own.', max_length=80),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Filled in when a named contributor row is claimed or attached.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
