# Generated by Django 5.1.15 on 2026-05-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_clear_unverified_orcid_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='placeholder_doi',
        ),
        migrations.AddField(
            model_name='project',
            name='doi',
            field=models.CharField(blank=True, help_text="Optional. The project's DOI as a bare identifier (e.g. 10.5281/zenodo.1234567). If you've deposited this work on Zenodo, OSF, Figshare, or an institutional repository, paste the DOI here. Leave blank if you don't have one yet.", max_length=120),
        ),
    ]
