# Generated by Django 5.1.15 on 2026-05-06 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_placeholder_doi_project_doi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('zenodo', 'Zenodo')], default='zenodo', max_length=40)),
                ('sandbox', models.BooleanField(default=True)),
                ('deposition_id', models.CharField(blank=True, max_length=80)),
                ('bucket_url', models.URLField(blank=True)),
                ('record_id', models.CharField(blank=True, max_length=80)),
                ('concept_id', models.CharField(blank=True, max_length=80)),
                ('doi', models.CharField(blank=True, max_length=120)),
                ('concept_doi', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('error', 'Error')], default='draft', max_length=20)),
                ('last_response', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_deposits', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['provider', 'sandbox', 'state'], name='projects_deposit_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'provider', 'sandbox'), name='unique_project_deposit_per_provider_mode')],
            },
        ),
    ]
