# Generated by Django 5.1.15 on 2026-05-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_normalize_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional. Upload a cover image (PNG/JPG/WebP). Max 10 MiB. OSPREY will downscale and re-encode it to WebP automatically.', null=True, upload_to='projects/cover/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Optional. Link to a cover image hosted elsewhere. OSPREY will fetch and re-encode it to WebP. Prefer the upload below if you have the file locally.'),
        ),
    ]
