# Generated by Django 5.1.15 on 2026-05-22 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding',
            field=models.TextField(blank=True, help_text='Funding sources, grants, or sponsoring programs that supported this project. Free text. List multiple sources one per line.'),
        ),
        migrations.AddField(
            model_name='project',
            name='publications',
            field=models.TextField(blank=True, help_text='Papers, talks, or reports that used this project. Free text. One reference per line; include a URL or DOI when you have one.'),
        ),
        migrations.AddField(
            model_name='project',
            name='self_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Submitter's honest self-rating on a 1-10 scale. 1-3: record of what did not work. 4-6: usable with caveats; expect work to integrate. 7-9: production-ready in its intended setting. 10: trusted on a mission-critical deployment.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='institution',
            field=models.TextField(blank=True, help_text='Institutions or labs that this project belongs to. Free text. List multiple affiliations one per line or separated by commas.'),
        ),
    ]
