# Generated by Django 5.1.15 on 2026-05-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_funding_project_publications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='affiliation',
            field=models.CharField(blank=True, default='', help_text='Institution this person was affiliated with for this project. Free text. Different contributors can list different institutions.', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='self_rating_note',
            field=models.TextField(blank=True, help_text="Optional. Brief explanation of the rating, especially when it is low. For example: 'works but power supply design has a known bug that needs fixing.'"),
        ),
    ]
