# Generated by Django 5.1.15 on 2026-05-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_contribution_affiliation_project_self_rating_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wiki_requires_approval',
            field=models.BooleanField(default=False, help_text='When true, non-maintainer wiki edits are queued as pending revisions instead of being published directly.'),
        ),
    ]
