# Generated by Django 5.1.15 on 2026-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_wiki_requires_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='wiki_requires_approval',
            field=models.BooleanField(default=True, help_text='When true, edits from non-maintainers are queued as pending suggestions for review. Pending suggestions are still publicly visible on the page so others can see proposed changes.'),
        ),
    ]
