# Generated by Django 5.1.15 on 2026-05-24 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0001_initial'),
        ('projects', '0022_alter_project_wiki_requires_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='attestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='attestations.attestation'),
        ),
        migrations.AddField(
            model_name='citation',
            name='source',
            field=models.CharField(choices=[('maintainer', 'Maintainer-added'), ('user', 'User-submitted'), ('attestation', 'From attestation')], default='maintainer', max_length=20),
        ),
        migrations.AddField(
            model_name='citation',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_citations', to=settings.AUTH_USER_MODEL),
        ),
    ]
