# Generated by Django 5.1.15 on 2026-06-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_remove_citation_attestation_citation_use_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_staff_hidden',
            field=models.BooleanField(default=False, help_text="Staff-only takedown flag. When true, the project is invisible to everyone except staff, regardless of the owner's visibility setting."),
        ),
    ]
