# Generated by Django 5.1.15 on 2026-09-03 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='self_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Self-assessed maturity on the 1-10 ladder defined in MATURITY_LEVELS. Levels are cumulative: a level counts only if all lower levels also hold.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='self_rating_note',
            field=models.TextField(blank=True, help_text='Optional. A sentence or two on why the project sits at its maturity level.'),
        ),
    ]
