# Generated by Django 5.1.15 on 2026-09-04 01:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_project_self_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineageedge',
            options={'ordering': ['-declared_at']},
        ),
        migrations.RemoveConstraint(
            model_name='lineageedge',
            name='unique_lineage_edge',
        ),
        migrations.AddField(
            model_name='lineageedge',
            name='child_version',
            field=models.ForeignKey(blank=True, help_text='Which version of the child made the claim. Set at publish.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineage_as_child', to='projects.projectdepositversion'),
        ),
        migrations.AddField(
            model_name='lineageedge',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When the claim went live and the parent was notified. Null while the child is still a draft.', null=True),
        ),
        migrations.AddField(
            model_name='lineageedge',
            name='declared_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lineageedge',
            name='declared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineage_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineageedge',
            name='dispute_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lineageedge',
            name='parent_version',
            field=models.ForeignKey(blank=True, help_text='Which published version of the parent the claim points at.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineage_as_parent', to='projects.projectdepositversion'),
        ),
        migrations.AddField(
            model_name='lineageedge',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineageedge',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting confirmation'), ('accepted', 'Confirmed'), ('auto_accepted', 'Confirmed (no objection)'), ('disputed', 'Disputed by the parent project'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lineageedge',
            name='relation',
            field=models.CharField(choices=[('derived_from', 'derived from'), ('uses', 'uses')], default='derived_from', max_length=40),
        ),
    ]
