# Generated by Django 5.1.15 on 2026-09-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_lineage_legacy_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineageedge',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disputed', 'Disputed by the parent project'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
    ]
