# Generated by Django 5.1.15 on 2026-09-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_lineage_dispute_only_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='claim_status',
            field=models.CharField(choices=[('unclaimed', 'Not invited'), ('invited', 'Invited'), ('verified', 'Verified'), ('declined', 'Declined'), ('disputed', 'Removal requested')], default='unclaimed', max_length=12),
        ),
        migrations.AddField(
            model_name='contribution',
            name='editor',
            field=models.BooleanField(default=False, help_text='Owner-granted edit access. Takes effect only once the row is verified.'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
