# Generated by Django 5.1.15 on 2026-09-04 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_contribution_claim_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pending_owner',
            field=models.ForeignKey(blank=True, help_text='Ownership transfer offered to this user; takes effect only when they accept. One pending transfer at a time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_ownerships', to=settings.AUTH_USER_MODEL),
        ),
    ]
