# Generated by Django 5.1.15 on 2026-09-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_alter_contribution_claim_status_zenodojob'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='origin',
            field=models.CharField(choices=[('native', 'Native (published through OSPREY)'), ('registered', "Registered (the authors' own Zenodo record)"), ('indexed', 'Indexed entry (ownerless reference)')], db_index=True, default='native', max_length=16),
        ),
        migrations.AddField(
            model_name='projectdeposit',
            name='in_community',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdeposit',
            name='managed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectdeposit',
            name='zenodo_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
