# Generated by Django 5.1.15 on 2026-09-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_project_origin_registered_deposits'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='license_check',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='license_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='origin',
            field=models.CharField(choices=[('native', 'Native (published through OSPREY)'), ('registered', "Registered (the authors' own Zenodo record)")], db_index=True, default='native', max_length=16),
        ),
    ]
