# Generated by Django 5.1.15 on 2026-09-29 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_project_origin_registered_deposits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_id',
            field=models.CharField(blank=True, help_text='DOI, owner/repo, or Zenodo concept id at the source.', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='files_url',
            field=models.URLField(blank=True, help_text='Where the design files live.'),
        ),
        migrations.AddField(
            model_name='project',
            name='files_url_source',
            field=models.CharField(blank=True, choices=[('spec_table', 'Journal specifications table'), ('record', 'Zenodo record'), ('repo', 'Repository'), ('body_scan', 'Found in article body'), ('staff', 'Entered by staff')], max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='gate_files',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='gate_license',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='index_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='index_state',
            field=models.CharField(choices=[('held', 'Held for review'), ('live', 'Live')], default='live', max_length=8),
        ),
        migrations.AddField(
            model_name='project',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='listed_by',
            field=models.ForeignKey(blank=True, help_text='Who submitted the entry. Empty for staff imports.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='oshwa_uid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='published_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(blank=True, choices=[('zenodo', 'Zenodo'), ('github', 'GitHub'), ('hardwarex', 'HardwareX'), ('joh', 'Journal of Open Hardware'), ('other', 'Other')], max_length=24),
        ),
        migrations.AddField(
            model_name='project',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='project_unique_source_external_id'),
        ),
    ]
