# Generated by Django 5.1.15 on 2026-09-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_project_indexed_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files_url_source',
            field=models.CharField(blank=True, choices=[('spec_table', 'Journal specifications table'), ('record', 'Zenodo record'), ('repo', 'Repository'), ('body_scan', 'Found in article body'), ('staff', 'Entered by staff'), ('submitter', 'Entered by the submitter')], max_length=16),
        ),
    ]
