# Generated by Django 5.1.15 on 2026-09-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_project_origin_two_kinds_license_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner_activity_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='provided_as_is',
            field=models.BooleanField(default=False),
        ),
    ]
