# Generated by Django 5.1.15 on 2026-10-06 12:04

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_project_provided_as_is_mute'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='full',
            field=models.ImageField(blank=True, upload_to=projects.models.project_image_upload_to),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='kind',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('readme', 'README')], db_index=True, default='gallery', max_length=8),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=projects.models.project_image_upload_to),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
