# Generated by Django 5.1.15 on 2026-09-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_project_files_url_source_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='license_check',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='license_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
