# Generated by Django 5.1.15 on 2026-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_project_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zenodojob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=10),
        ),
    ]
