# Generated by Django 5.1.15 on 2026-05-24 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0021_project_wiki_requires_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.TextField(help_text='What did you do with this project?')),
                ('used_at', models.CharField(blank=True, default='', help_text='When or where you used it. Free text.', max_length=80)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('hidden', 'Hidden by maintainer')], default='public', max_length=10)),
                ('endorsement', models.CharField(blank=True, choices=[('', 'Not endorsed'), ('acknowledged', 'Acknowledged'), ('featured', 'Featured')], default='', max_length=20)),
                ('endorsed_at', models.DateTimeField(blank=True, null=True)),
                ('moderator_note', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations', to=settings.AUTH_USER_MODEL)),
                ('endorsed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', 'visibility', '-created_at'], name='attestation_project_f3a2c9_idx')],
            },
        ),
    ]
