# Generated by Django 5.1.15 on 2026-06-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_reports', '0003_delete_attestation_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usereport',
            new_name='use_reports_project_c02e69_idx',
            old_name='attestation_project_23e47b_idx',
        ),
    ]
