# Generated by Django 5.1.15 on 2026-05-01 20:03

import django.db.models.deletion
import feedback.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='What the user wrote. Limited to 4000 characters by the form.')),
                ('page_url', models.URLField(blank=True, help_text='The page the widget was opened on.', max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('os', models.CharField(blank=True, max_length=80)),
                ('viewport_w', models.PositiveIntegerField(blank=True, null=True)),
                ('viewport_h', models.PositiveIntegerField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, help_text='Optional. Captured client-side and may include user annotations.', null=True, upload_to=feedback.models._screenshot_upload_to)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('resolved', 'Resolved'), ('wontfix', "Won't fix")], default='new', max_length=12)),
                ('admin_notes', models.TextField(blank=True, help_text='Triage notes. Not shown to the submitter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
