# Generated by Django 5.1.15 on 2026-09-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('suggestion', 'Suggestion'), ('privacy', 'Privacy request')], default='suggestion', help_text='Suggestions come from the suggestion box; privacy requests come from the form linked in the Privacy Policy.', max_length=12),
        ),
    ]
