# Generated by Django 5.1.15 on 2026-09-04 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='opened_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who opened this thread, for outreach threads. Null when the user opened it themselves.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_staff_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reopen_requested',
            field=models.BooleanField(default=False, help_text='The user asked to reopen this closed thread. Staff reopen (set an open status) or dismiss the request.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('suggestion', 'Suggestion'), ('privacy', 'Privacy request'), ('outreach', 'Staff outreach')], default='suggestion', help_text='Suggestions come from the suggestion box; privacy requests come from the form linked in the Privacy Policy.', max_length=12),
        ),
    ]
