# Generated by Django 5.1.15 on 2026-09-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_opened_by_feedback_reopen_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='client_errors',
            field=models.TextField(blank=True, help_text='Recent uncaught JS errors on the page, captured by the widget.'),
        ),
    ]
