# Generated by Django 5.1.15 on 2026-06-01 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0001_initial'),
        ('projects', '0023_citation_attestation_citation_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='attestation',
            name='endorsed_by',
        ),
        migrations.RemoveField(
            model_name='attestation',
            name='project',
        ),
        migrations.CreateModel(
            name='UseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.TextField(help_text='What did you do with this project?')),
                ('used_at', models.CharField(blank=True, default='', help_text='When or where you used it. Free text.', max_length=80)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('hidden', 'Hidden by staff')], default='public', max_length=10)),
                ('moderator_note', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_reports', to='projects.project')),
            ],
            options={
                'verbose_name': 'use report',
                'verbose_name_plural': 'use reports',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
