# Generated by Django 5.1.15 on 2026-06-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0002_remove_attestation_author_and_more'),
        ('projects', '0024_remove_citation_attestation_citation_use_report_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attestation',
        ),
        migrations.AddIndex(
            model_name='usereport',
            index=models.Index(fields=['project', 'visibility', '-created_at'], name='attestation_project_23e47b_idx'),
        ),
    ]
