# Generated by Django 5.1.15 on 2026-06-03 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_suspend', 'Suspend user'), ('user_reinstate', 'Reinstate user'), ('user_purge_content', 'Purge user content'), ('project_hide', 'Hide project'), ('project_unhide', 'Unhide project'), ('report_action', 'Action report'), ('report_dismiss', 'Dismiss report'), ('other', 'Other')], max_length=40)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, max_length=300)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='moderation__created_5b13b7_idx'), models.Index(fields=['target_ct', 'target_id'], name='moderation__target__3e4657_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField()),
                ('target_repr', models.CharField(blank=True, help_text='Snapshot of target title/url at the time of report.', max_length=300)),
                ('context_url', models.CharField(blank=True, help_text='URL the reporter was on when filing the report.', max_length=500)),
                ('category', models.CharField(choices=[('spam', 'Spam or junk'), ('abuse', 'Abuse or harassment'), ('copyright', 'Copyright or licensing concern'), ('off_topic', 'Off-topic for OSPREY'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('target_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='moderation__status_282342_idx'), models.Index(fields=['target_ct', 'target_id'], name='moderation__target__e6c8d6_idx')],
            },
        ),
    ]
