# Generated by Django 5.1.15 on 2026-04-30 22:45

import people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=people.models._avatar_upload_to),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Optional short bio. Markdown is supported.'),
        ),
    ]
