# Generated by Django 5.1.15 on 2026-04-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_profile_avatar_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orcid_placeholder',
            field=models.CharField(blank=True, db_index=True, help_text='String form of an ORCID iD; becomes the verified iD once OAuth lands.', max_length=40),
        ),
    ]
