# Generated by Django 5.1.15 on 2026-05-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_delete_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertag_locked',
            field=models.BooleanField(default=False, help_text="Whether the user's local @ tag has been finalized."),
        ),
    ]
