# Generated by Django 5.1.15 on 2026-05-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_profile_usertag_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.TextField(blank=True, help_text='Institutions or labs you are affiliated with. Free text. List multiple affiliations one per line or separated by commas.'),
        ),
    ]
