# Generated by Django 5.1.15 on 2026-06-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_profile_avatar_focal_x_profile_avatar_focal_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp the account was suspended by staff. The auth.User.is_active flag is the gate.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='suspended_reason',
            field=models.TextField(blank=True, help_text='Staff-only note explaining why this account is suspended.'),
        ),
    ]
