# Generated by Django 5.1.15 on 2026-09-30 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('new', 'New accounts only'), ('all', 'Every sign-in, existing accounts too')], default='new', max_length=4)),
                ('allowlist', models.TextField(blank=True, default='', help_text='ORCID iDs that bypass the check, one per line.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sign-up gate',
                'verbose_name_plural': 'sign-up gate',
            },
        ),
    ]
