# Generated by Django 5.1.15 on 2026-06-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('feedback_reply', 'Feedback reply'), ('project_comment', 'Project comment'), ('use_report', 'Project use report'), ('wiki_suggestion', 'Wiki suggestion'), ('generic', 'General')], default='generic', max_length=40),
        ),
    ]
