# Generated by Django 5.1.15 on 2026-08-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch. When off (or when keys are missing), outgoing mail is written to the server log instead of being sent.')),
                ('from_email', models.CharField(blank=True, default='', help_text='Sender address, e.g. "OSPREY <notify@osprey.phalkon.io>".', max_length=254)),
                ('mailjet_api_key', models.CharField(blank=True, default='', max_length=128)),
                ('mailjet_secret_key', models.CharField(blank=True, default='', max_length=128)),
                ('test_recipient', models.EmailField(blank=True, default='', help_text='Where the “send test email” admin action delivers.', max_length=254)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_result', models.CharField(blank=True, default='', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'email settings',
                'verbose_name_plural': 'email settings',
            },
        ),
    ]
