# Generated by Django 5.1.15 on 2026-08-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emailsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='mailjet_api_key',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='mailjet_secret_key',
        ),
    ]
