# Generated by Django 5.1.15 on 2026-08-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_emailsettings_mailjet_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Master switch. When off (or when the delivery provider is not configured), outgoing mail is written to the server log instead of being sent.'),
        ),
    ]
