# Generated by Django 5.1.15 on 2026-09-01 12:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_emailsettings_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Master switch for all notification email to this user.')),
                ('projects', models.CharField(choices=[('off', 'Off'), ('immediate', 'Immediate'), ('daily', 'Daily summary'), ('weekly', 'Weekly summary')], default='daily', max_length=10)),
                ('replies', models.CharField(choices=[('off', 'Off'), ('immediate', 'Immediate'), ('daily', 'Daily summary'), ('weekly', 'Weekly summary')], default='daily', max_length=10)),
                ('follows', models.CharField(choices=[('off', 'Off'), ('immediate', 'Immediate'), ('daily', 'Daily summary'), ('weekly', 'Weekly summary')], default='daily', max_length=10)),
                ('account', models.CharField(choices=[('off', 'Off'), ('immediate', 'Immediate')], default='immediate', max_length=10)),
                ('staff', models.CharField(choices=[('off', 'Off'), ('immediate', 'Immediate'), ('daily', 'Daily summary'), ('weekly', 'Weekly summary')], default='immediate', max_length=10)),
                ('auto_follow_threads', models.BooleanField(default=True, help_text='Automatically follow threads you start or reply in.')),
                ('consented_at', models.DateTimeField(blank=True, help_text='When the user added their email address (the consent act).', null=True)),
                ('consent_source', models.CharField(blank=True, default='', help_text='Where the address was added: welcome flow or settings.', max_length=40)),
                ('last_daily_digest_at', models.DateTimeField(blank=True, null=True)),
                ('last_weekly_digest_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueuedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='', max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('body_text', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for', 'id'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_31928d_idx')],
            },
        ),
    ]
