# Generated by Django 5.1.15 on 2026-09-04 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationpreference_queuedemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Plain text. Sent as written, with the standard email footer appended.')),
                ('url', models.CharField(blank=True, help_text='Optional link shown with the notification, e.g. /about/.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Users reached in-app on the real send.')),
                ('emailed_count', models.PositiveIntegerField(default=0, help_text='Emails queued on the real send.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
