# Generated by Django 5.1.15 on 2026-09-04 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedemail',
            name='ephemeral',
            field=models.BooleanField(default=False, help_text='Delete this row after the send attempt settles, instead of keeping it as a delivery record.'),
        ),
        migrations.AddField(
            model_name='queuedemail',
            name='to_address',
            field=models.EmailField(blank=True, default='', help_text="Raw recipient for external mail only. Ephemeral rows are deleted right after sending so the address isn't kept.", max_length=254),
        ),
        migrations.AlterField(
            model_name='queuedemail',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for external mail (contributor invites), which carries its own to_address instead.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queued_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
