# Generated by Django 5.1.15 on 2026-09-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_queuedemail_ephemeral_queuedemail_to_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='new_projects',
            field=models.CharField(choices=[('off', 'Off'), ('immediate', 'Immediate'), ('daily', 'Daily summary'), ('weekly', 'Weekly summary')], default='weekly', help_text='Every new project published on OSPREY, not just ones from people you follow. Off hides them from the in-app inbox too.', max_length=10),
        ),
    ]
