# Generated by Django 5.1.15 on 2026-09-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notificationpreference_new_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoopHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'notifier heartbeat',
                'verbose_name_plural': 'notifier heartbeat',
            },
        ),
    ]
